// Sample transactions data
import ITransactions from "../interfaces/ITransactions.ts";

// @ts-expect-error no error
const transactions: ITransactions[] = [
  {
    id: 1,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 100,
    date: "2024-10-01",
    description: "Weekly groceries",
    cardNumber: "**** **** **** 1234",
  },
  {
    id: 2,
    transactionType: "credit",
    purpose: "salary",
    amount: 2000,
    date: "2024-10-02",
    description: "Monthly salary",
    cardNumber: "**** **** **** 5678",
  },
  {
    id: 3,
    transactionType: "debit",
    purpose: "medical expenses",
    amount: 150,
    date: "2024-10-03",
    description: "Doctor visit",
    cardNumber: "**** **** **** 1234",
  },
  {
    id: 4,
    transactionType: "debit",
    purpose: "clothing & accessories",
    amount: 75,
    date: "2024-10-04",
    description: "New shirt",
    cardNumber: "**** **** **** 2345",
  },
  {
    id: 5,
    transactionType: "debit",
    purpose: "traveling",
    amount: 250,
    date: "2024-10-05",
    description: "Train ticket",
    cardNumber: "**** **** **** 3456",
  },
  {
    id: 6,
    transactionType: "credit",
    purpose: "investment",
    amount: 500,
    date: "2024-10-06",
    description: "Stocks sold",
    cardNumber: "**** **** **** 4567",
  },
  {
    id: 7,
    transactionType: "debit",
    purpose: "subscription",
    amount: 15,
    date: "2024-10-07",
    description: "Streaming service",
    cardNumber: "**** **** **** 5678",
  },
  {
    id: 8,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 80,
    date: "2024-10-08",
    description: "Weekly groceries",
    cardNumber: "**** **** **** 6789",
  },
  {
    id: 9,
    transactionType: "credit",
    purpose: "donation/charity/zakat",
    amount: 200,
    date: "2024-10-09",
    description: "Charity donation",
    cardNumber: "**** **** **** 7890",
  },
  {
    id: 10,
    transactionType: "debit",
    purpose: "loan",
    amount: 300,
    date: "2024-10-10",
    description: "Loan payment",
    cardNumber: "**** **** **** 8901",
  },
  {
    id: 11,
    transactionType: "debit",
    purpose: "medical expenses",
    amount: 120,
    date: "2024-10-11",
    description: "Pharmacy purchase",
    cardNumber: "**** **** **** 9012",
  },
  {
    id: 12,
    transactionType: "credit",
    purpose: "transfer to own account",
    amount: 1000,
    date: "2024-10-12",
    description: "Transfer from savings",
    cardNumber: "**** **** **** 0123",
  },
  {
    id: 13,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 60,
    date: "2024-10-13",
    description: "Snacks",
    cardNumber: "**** **** **** 1234",
  },
  {
    id: 14,
    transactionType: "credit",
    purpose: "salary",
    amount: 2500,
    date: "2024-10-14",
    description: "Bonus",
    cardNumber: "**** **** **** 5678",
  },
  {
    id: 15,
    transactionType: "debit",
    purpose: "clothing & accessories",
    amount: 120,
    date: "2024-10-15",
    description: "Winter coat",
    cardNumber: "**** **** **** 2345",
  },
  {
    id: 16,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 95,
    date: "2024-10-16",
    description: "Monthly groceries",
    cardNumber: "**** **** **** 6789",
  },
  {
    id: 17,
    transactionType: "credit",
    purpose: "investment",
    amount: 750,
    date: "2024-10-17",
    description: "Mutual fund dividend",
    cardNumber: "**** **** **** 8901",
  },
  {
    id: 18,
    transactionType: "debit",
    purpose: "traveling",
    amount: 500,
    date: "2024-10-18",
    description: "Flight ticket",
    cardNumber: "**** **** **** 9012",
  },
  {
    id: 19,
    transactionType: "debit",
    purpose: "medical expenses",
    amount: 200,
    date: "2024-10-19",
    description: "Dental checkup",
    cardNumber: "**** **** **** 0123",
  },
  {
    id: 20,
    transactionType: "debit",
    purpose: "vendor",
    amount: 300,
    date: "2024-10-20",
    description: "Supplies purchase",
    cardNumber: "**** **** **** 2345",
  },
  {
    id: 21,
    transactionType: "credit",
    purpose: "transfer to family account",
    amount: 1500,
    date: "2024-10-21",
    description: "Family support",
    cardNumber: "**** **** **** 5678",
  },
  {
    id: 22,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 110,
    date: "2024-10-22",
    description: "Dinner out",
    cardNumber: "**** **** **** 6789",
  },
  {
    id: 23,
    transactionType: "debit",
    purpose: "subscription",
    amount: 30,
    date: "2024-10-23",
    description: "Online courses",
    cardNumber: "**** **** **** 7890",
  },
  {
    id: 24,
    transactionType: "credit",
    purpose: "salary",
    amount: 2200,
    date: "2024-10-24",
    description: "Monthly salary",
    cardNumber: "**** **** **** 8901",
  },
  {
    id: 25,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 85,
    date: "2024-10-25",
    description: "Lunch with friends",
    cardNumber: "**** **** **** 9012",
  },
  {
    id: 26,
    transactionType: "debit",
    purpose: "traveling",
    amount: 300,
    date: "2024-10-26",
    description: "Hotel booking",
    cardNumber: "**** **** **** 0123",
  },
  {
    id: 27,
    transactionType: "credit",
    purpose: "donation/charity/zakat",
    amount: 150,
    date: "2024-10-27",
    description: "Community donation",
    cardNumber: "**** **** **** 2345",
  },
  {
    id: 28,
    transactionType: "debit",
    purpose: "loan",
    amount: 200,
    date: "2024-10-28",
    description: "Loan payment",
    cardNumber: "**** **** **** 5678",
  },
  {
    id: 29,
    transactionType: "credit",
    purpose: "transfer to own account",
    amount: 1200,
    date: "2024-10-29",
    description: "Savings transfer",
    cardNumber: "**** **** **** 6789",
  },
  {
    id: 30,
    transactionType: "debit",
    purpose: "food & groceries",
    amount: 70,
    date: "2024-10-30",
    description: "Snack shopping",
    cardNumber: "**** **** **** 7890",
  },
];

export default transactions;
